import { Router } from "express";
import { listItems, getItem, createItem, updateItem, deleteItem, hardDeleteItem, listTrash, restoreItem, listFolders, createFolder, updateFolder, deleteFolder, getStats } from "../controllers/vaultController";
import { authenticate } from "../middleware/auth";
import { validate } from "../middleware/validate";
const router = Router();
router.use(authenticate);
router.get("/stats", getStats);
router.get("/items", listItems);
router.get("/items/:id", getItem);
router.post("/items", validate({ type: { required: true, type: "string", enum: ["password","secret","note","card","identity","media"] }, title: { required: true, type: "string", minLength: 1, maxLength: 255 } }), createItem);
router.put("/items/:id", updateItem);
router.delete("/items/:id", deleteItem);
router.delete("/items/:id/permanent", hardDeleteItem);
router.post("/items/:id/restore", restoreItem);
router.get("/trash", listTrash);
router.get("/folders", listFolders);
router.post("/folders", validate({ name: { required: true, type: "string", minLength: 1, maxLength: 100 } }), createFolder);
router.put("/folders/:id", updateFolder);
router.delete("/folders/:id", deleteFolder);
export default router;